<a href="https://colab.research.google.com/github/dschumilow/portafolio/blob/main/Clase_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#POO Principios Abstraccion y Encapsulamiento
#Ejemplo
class CuentaBancaria:
    def __init__(self, titular, saldo=0): #definicion objeto
        self.titular = titular
        self.__saldo = saldo #atributo privado

    def depositar(self, monto): #metodo depositar
      if monto > 0:
        self._saldo += monto #incremento, si anteriormente el saldo era 0 y se incremento entonces nos da 0 +100

    def consultar_saldo(self): #metodo consultar saldo
      return self.__saldo

cuenta = CuentaBancaria("Juan", 100)
cuenta.depositar(50)
print(cuenta.consultar_saldo()) #imprime 150

150


In [ ]:
#Ejemplo de clase con constructor e instanciacion de objetos
class Persona:
    def __init__(self, nombre, edad): #constructor
        self.nombre = nombre
        self.edad = edad

    def saludar(self): #metodo
        print(f"Hola, mi nombre es {self.nombre} y tengo {self.edad} años.")

#instanciacion de objetos
persona1 = Persona("Juan", 25)
persona2 = Persona("Maria", 30)

persona1.saludar()
persona2.saludar()



In [ ]:
texto = 'hola mundo'
print(texto.upper())
print(texto.lower())
print(texto.find("Mundo"))
print(replace('mundo', 'python'))
palabras = texto.split()

In [ ]:
#EVALUACION PRACTICA MODULO 2

In [ ]:
#1 Definir variables basicas y tipos de datos
libros=[{'titulo':'Finanzas','autor':'Pedro','precio':50.00,'stock':1},
 {'titulo':'Dune','autor':'Frank Herbert','precio':11.99,'stock':50},
        {'titulo':'La casa de los espiritus','autor':'Isabel Allende','precio':20.00,'stock':30},
        {'titulo':'La Biblia','autor':'Varios','precio':200.00,'stock':25},
        {'titulo':'100 años de soledad','autor':'Gabriel Garcia Marquez','precio':25.00,'stock':10}]
print(libros)



In [ ]:
#2 Control de flujo
def mostrar_libros_disponibles():
    for libro in libros: #libro la variable que almacena el ciclo for
        if libro.get('stock')>1:
          print(libro)

mostrar_libros_disponibles()

In [ ]:
#2 Control de flujo
def mostrar_libros_disponibles():
    for libro in libros: #libro la variable que almacena el ciclo for
        if libro['stock']>1:
          print(libro)

mostrar_libros_disponibles()

{'titulo': 'Dune', 'autor': 'Frank Herbert', 'precio': 11.99, 'stock': 50}
{'titulo': 'La casa de los espiritus', 'autor': 'Isabel Allende', 'precio': 20.0, 'stock': 30}
{'titulo': 'La Biblia', 'autor': 'Varios', 'precio': 200.0, 'stock': 25}
{'titulo': '100 años de soledad', 'autor': 'Gabriel Garcia Marquez', 'precio': 25.0, 'stock': 10}


In [ ]:
#3 Condiciones y operadores
minimo=float(input('Ingrese el precio minimo: '))
maximo=float(input('Ingrese el precio maximo: '))

for libro in libros: #for que va a recorrer libro en libros
    if libro.get('precio')>=minimo and libro.get('precio')<=maximo: #finalizar con dos puntos para la accion final
        print(libro)

In [ ]:
#MODULO 3 NUMPY
import numpy as np

numeros=[1,2,3,4,5,6,7,8,9,10]
print(numeros)


lista_python=list(range(100))
print(lista_python[0])

#arreglo en python
arreglo_python=np.arange(1,100)
print(arreglo_python)

duplicados=[numero*2 for numero in numeros]
print(duplicados)
print(f 'el proceso tuvo una duracion de:{time.time()-inicio} segundos ')

In [ ]:
#MODULO 3 NUMPY
import numpy as np

numeros=[1,2,3,4,5,6,7,8,9,10]
print(numeros)

inicio = time.time()
lista_python=list(range(1000000))
print(lista_python[0])
print(f'el proceso tuvo una duracion de:{time.time()-inicio} segundos ')

#arreglo en python
inicio2=time.time()
arreglo_python=np.arange(1,1000000)
print(arreglo_python[5])
print(f'el proceso tuvo una duracion de:{time.time()-inicio2} segundos ')

duplicados=[numero*2 for numero in numeros]
print(duplicados)


In [ ]:
#Arreglo 2
import numpy as np

a=np.array([1,2,3]) #es un vector
b=np.array([4,5,6]) #es un vector
c=a+b
print(c)

suma2=np.sum([a,b])
print(suma2)

producto=a*b
print(producto)

punto=np.dot(a,b)
print(punto)

#creacion de un vector

vector=np.array([1,2,3,4,5])
print(f'Dimensiones: {vector.shape}')
print(f'Tipo de datos: {vector.dtype}')

#creacion de una matriz
matriz=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matriz)
print(f'Dimensiones: {matriz.shape}')

#creacion de tensor 3D (2X2X2)
tensor=np.array([[[1,2],[3,4]],[[5,6],[7,8]]]) #matriz con otr matriz
print(tensor)
print(f'Dimensiones: {tensor.shape}')


In [ ]:
#creacion de matricez

import numpy as np

arreglo=np.arange(0,10,2) #tira una lista que incluye el inicio pero no el fin
#arreglo=np.arange(inicio,fin,paso)
print(arreglo)

matriz_ceros=np.zeros((2,3))
print(matriz_ceros)

matriz_unos=np.ones((2,3))
print(matriz_unos)

matriz_random=np.random.randint(1,100,(3,3))
print(matriz_random)


[0 2 4 6 8]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[76 41 76]
 [ 3 82 16]
 [71 83 18]]


In [ ]:
arr=np.array([10,20,30,40,50,60,70])

#indexacion basica
print('Elemento en pos 2: ',arr[2])

#Slicing[start:stop:step]
print('Elementos del 1 al 4: ',arr[1:5])
print('Elementos pares: ',arr[::2]) #muestra los elementos en las posiciones pares

#Indexacion booleana
condicion=arr>35
print('Condicion arr:35: ',condicion)


#Valores que cumplen con la condicion
condicion=arr>35
print('Elementos mayores a 35: ',arr[condicion])

#Crear una matriz de 3x3 con los numeros del 1 al 9
mat=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mat)

#Acceder a un elemento de la matriz
print(mat[1,2])
print(mat[0])
print(mat[0,:])
print(mat[:,2])
print(mat[:,-1])

